name: BlahajPaperized
version: '1.0'
main: de.cjdev.blahajPaperized.BlahajPaperized
api-version: '1.21'
load: STARTUP
authors: [ CJDev ]
description: The Blahaj mod, now for PaperMC!
website: https://modrinth.com/plugin/blahaj-paperized
dependencies:
  server:
    PaperModAPI:
      required: true
      load: BEFORE
    RecipeAPI:
      required: true
      load: BEFORE
